version: '3.1'

services:
  app:
    image: '06bb904513fa'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_USER=
      - DB_PASSWORD=
      - DB_URL= jdbc:postgresql://db
    depends_on:
      - db
  db:
        image: 'postgres'
        container_name: db
        expose:
        - '5432'
        environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=password


